c%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
c
c  pregres.inc
c
c%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      character*40 coal1fnam,coal2fnam,rockfnam
      common/pregres/ col1(nsize1,nsize2),nc1,coal1fnam,
     &                col2(nsize1,nsize2),nc2,coal2fnam,
     &                 rok(nsize1,nsize2),nrok, rockfnam,
     &                 dp,spangle
