c%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
c
c  prop.inc
c
c%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
c
      common /prop/ rhocol,ww,wc,wa,wv,ycp,yap,ybp,wfash,rhorok,
     &              rhobeda,rhobedc,rhobedr,emis,wmc,wmp,wmw,wwrok,
     &              scond,ag,tag,yp(5),pgasfrac,epscoal,permcoal,
     &              prandtl,dp0,viscc(2),tfail,tamb,tsteam,dhv,
     &              glosfrac,storage,pinitial
